2021-09-16 16:29:09  [ Thread-2:1 ] - [ ERROR ]  pers.chris.dbSync.exception.FieldMapException: DstField, nae doesn't exist
2021-09-16 16:29:12  [ Thread-2:2993 ] - [ ERROR ]  org.postgresql.util.PSQLException: ERROR: column "nae" of relation "users" does not exist
  位置：19
2021-09-16 16:29:12  [ Thread-2:3000 ] - [ ERROR ]  org.postgresql.util.PSQLException: ERROR: column "nae" of relation "users" does not exist
  位置：19
2021-09-16 16:31:44  [ Thread-2:0 ] - [ ERROR ]  pers.chris.dbSync.exception.FieldMapException: DstField, nae doesn't exist
2021-09-16 16:32:17  [ Thread-2:0 ] - [ ERROR ]  pers.chris.dbSync.exception.FieldMapException: DstField, nae doesn't exist
2021-09-16 16:36:31  [ Thread-2:11 ] - [ ERROR ]  org.postgresql.util.PSQLException: ERROR: column "nam" of relation "users" does not exist
  位置：39
2021-09-16 16:36:31  [ Thread-2:26 ] - [ ERROR ]  org.postgresql.util.PSQLException: ERROR: column "nam" of relation "users" does not exist
  位置：39
